# ---prod---
css:
  style: 'https://static.tumblr.com/dlluljv/nQErtguz2/style.css'
js:
  main: 'https://static.tumblr.com/dlluljv/MpBrluz1v/main.js'
  resizer: 'https://static.tumblr.com/dlluljv/xvNrluz1s/iframeresizer.contentwindow.js'
# ---local---
# css:
#   style: './css/style.css'
# js:
#   main: './js/main.js'
#   resizer: './js/iframeResizer.contentWindow.js'
